name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
  - cron:  '00 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker build . --file otel-javaagent-1.23.Dockerfile --tag demtag/otel-javaagent:1.23
        docker build . --file otel-javaagent-1.24.Dockerfile --tag demtag/otel-javaagent:1.24
    - name: Login to registry
      run: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: |
        docker push demtag/otel-javaagent:1.23
        docker push demtag/otel-javaagent:1.24
